export const RULES = [
  { id:'secret-exposure', severity:'critical', cwe:'CWE-798', title:'Hard-coded credential', pattern:/(?:api[_-]?key|secret|token|password)\s*[:=]\s*["'`](?!process\.env|\$\{|<)[A-Za-z0-9_\-\/+=]{12,}["'`]/gi, explain:'A credential appears embedded in source code.', proof:'Credential material is recoverable by anyone who can read the repository.' },
  { id:'command-injection', severity:'critical', cwe:'CWE-78', title:'Shell command uses untrusted input', pattern:/(?:exec|execSync)\s*\(\s*(?:`[^`]*\$\{|[^)]*(?:req\.|request\.|input|query|params))/gi, explain:'Untrusted input is interpolated into a shell command.', proof:'An attacker-controlled metacharacter can alter the executed command.' },
  { id:'unsafe-code-execution', severity:'critical', cwe:'CWE-95', title:'Dynamic code execution', pattern:/\b(?:eval|Function)\s*\(\s*(?!["'`]use strict)/g, explain:'Dynamic code execution can run attacker-controlled JavaScript.', proof:'The supplied string is interpreted as executable code.' },
  { id:'auth-bypass', severity:'high', cwe:'CWE-862', title:'Authentication or authorization bypass', pattern:/(?:skipAuth|disableAuth|authRequired|verifyToken)\s*[:=]\s*(?:true|false|null)/gi, explain:'A security-sensitive authentication control is disabled or bypassed.', proof:'The affected route may execute without a verified identity.' },
  { id:'permissive-cors', severity:'high', cwe:'CWE-942', title:'Unrestricted CORS policy', pattern:/(?:origin\s*:\s*["'`]\*["'`]|Access-Control-Allow-Origin["'`]?,\s*["'`]\*)/gi, explain:'Wildcard cross-origin access can expose authenticated data.', proof:'Any origin can issue cross-origin requests accepted by the service.' },
  { id:'tls-disabled', severity:'high', cwe:'CWE-295', title:'TLS verification disabled', pattern:/(?:rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0)/gi, explain:'Certificate verification is disabled.', proof:'A man-in-the-middle certificate will be accepted.' },
  { id:'weak-randomness', severity:'medium', cwe:'CWE-338', title:'Weak randomness in security context', pattern:/Math\.random\(\).{0,80}(?:token|secret|password|otp|nonce|session)|(?:token|secret|password|otp|nonce|session).{0,80}Math\.random\(\)/gi, explain:'Math.random is not cryptographically secure.', proof:'Outputs are predictable enough to be unsuitable for secrets.' },
  { id:'path-traversal', severity:'high', cwe:'CWE-22', title:'User-controlled filesystem path', pattern:/(?:readFile|writeFile|createReadStream|sendFile)\s*\([^\n]*(?:req\.|request\.|params|query)/gi, explain:'A request value reaches a filesystem operation without visible containment.', proof:'Traversal segments may access files outside the intended directory.' },
  { id:'sql-injection', severity:'critical', cwe:'CWE-89', title:'SQL query interpolation', pattern:/(?:query|execute)\s*\(\s*`[^`]*(?:\$\{(?:req\.|input|params|query)|SELECT|INSERT|UPDATE|DELETE)[^`]*`/gi, explain:'A SQL statement is assembled through string interpolation.', proof:'SQL metacharacters can change the query structure.' },
  { id:'prototype-pollution', severity:'high', cwe:'CWE-1321', title:'Unsafe dynamic property assignment', pattern:/\w+\s*\[\s*(?:req\.|input|key|path|prop)\w*\s*\]\s*=/gi, explain:'An attacker-controlled property name is assigned without blocking prototype keys.', proof:'__proto__ or constructor paths may modify object prototypes.' },
  { id:'open-redirect', severity:'medium', cwe:'CWE-601', title:'Unvalidated redirect target', pattern:/(?:res\.)?redirect\s*\(\s*(?:req\.|request\.|params|query|input)/gi, explain:'A request value controls a redirect destination.', proof:'An attacker can redirect users to an arbitrary origin.' },
  { id:'unsafe-deserialization', severity:'critical', cwe:'CWE-502', title:'Unsafe deserialization', pattern:/(?:serialize-javascript|node-serialize).*(?:unserialize|deserialize)|\bdeserialize\s*\(\s*(?:req\.|input)/gis, explain:'Untrusted data is deserialized by an unsafe mechanism.', proof:'Crafted serialized input may instantiate or execute unexpected objects.' }
];

export const SEVERITY_SCORE = { critical:4, high:3, medium:2, low:1, info:0 };
