import { promises as fs } from 'node:fs';
import path from 'node:path';

export async function analyzeSupplyChain(root,files,{network=true}={}){
  const findings=[];let lock;
  try{lock=JSON.parse(await fs.readFile(path.join(root,'package-lock.json'),'utf8'));}catch{return findings;}
  const trust=await readJson(path.join(root,'.patchproof','trust.json'))||{packages:{}};
  for(const [location,entry] of Object.entries(lock.packages||{})){
    if(!location.startsWith('node_modules/')||!entry.version)continue;const name=location.slice('node_modules/'.length);
    if(!entry.integrity&&!entry.link)findings.push(issue('lockfile-missing-integrity','high','package-lock.json',`Locked package ${name}@${entry.version} has no integrity digest.`,`lock-integrity:${name}@${entry.version}`,'Regenerate the lockfile from the official registry and commit its integrity field.','lockfile_verified'));
    const installed=await readJson(path.join(root,location,'package.json'));if(installed?.version&&installed.version!==entry.version)findings.push(issue('installed-version-drift','high',`${location}/package.json`,`Installed ${name}@${installed.version} differs from locked ${entry.version}.`,`installed:${name}`,'Run npm ci from the committed lockfile and investigate local modification.','installed_verified'));
    const trusted=trust.packages?.[name];
    if(network&&trusted){try{const response=await fetch(`https://registry.npmjs.org/${encodeURIComponent(name).replace('%40','@')}`,{signal:AbortSignal.timeout(3500)});if(response.ok){const data=await response.json();const current=(data.maintainers||[]).map(x=>x.name).sort();if(trusted.maintainers?.length&&JSON.stringify([...trusted.maintainers].sort())!==JSON.stringify(current))findings.push(issue('maintainer-change','high','package-lock.json',`Maintainer set changed for ${name}: expected [${trusted.maintainers.join(', ')}], registry reports [${current.join(', ')}].`,`maintainers:${name}:${current.join(',')}`,'Verify the ownership change out of band, then deliberately refresh the trust snapshot.','registry_verified'));const publisher=data.versions?.[entry.version]?._npmUser?.name||null;if(trusted.publisher&&publisher&&trusted.publisher!==publisher)findings.push(issue('publisher-change','high','package-lock.json',`Publisher changed for ${name}@${entry.version}: expected ${trusted.publisher}, registry reports ${publisher}.`,`publisher:${name}:${entry.version}:${publisher}`,'Verify the release publisher and package provenance before accepting the version.','registry_verified'));}}catch{}}
  }
  findings.push(...await verifyInstalledExports(root,files));return findings;
}

export async function createTrustSnapshot(root,{network=true}={}){
  const manifest=await readJson(path.join(root,'package.json'));if(!manifest)throw new Error('package.json not found');const names=Object.keys({...manifest.dependencies,...manifest.devDependencies}).sort();const packages={};
  for(const name of names){const installed=await readJson(path.join(root,'node_modules',name,'package.json'));const record={version:installed?.version||null,maintainers:[],publisher:null};if(network){try{const response=await fetch(`https://registry.npmjs.org/${encodeURIComponent(name).replace('%40','@')}`,{signal:AbortSignal.timeout(3500)});if(response.ok){const data=await response.json();record.maintainers=(data.maintainers||[]).map(x=>x.name).sort();record.latest=data['dist-tags']?.latest||null;const version=record.version||record.latest;record.publisher=data.versions?.[version]?._npmUser?.name||null;}}catch{}}packages[name]=record;}
  const snapshot={version:1,createdAt:new Date().toISOString(),packages};const dir=path.join(root,'.patchproof');await fs.mkdir(dir,{recursive:true});const output=path.join(dir,'trust.json');await fs.writeFile(output,JSON.stringify(snapshot,null,2)+'\n');return output;
}

async function verifyInstalledExports(root,files){const findings=[];for(const file of files.filter(f=>/\.[cm]?[jt]sx?$/.test(f))){const source=await fs.readFile(file,'utf8');for(const match of source.matchAll(/import\s*\{([^}]+)\}\s*from\s*["']([^"']+)["']/g)){const spec=match[2];if(spec.startsWith('.'))continue;const name=spec.startsWith('@')?spec.split('/').slice(0,2).join('/'):spec.split('/')[0];const pkgRoot=path.join(root,'node_modules',name);const pkg=await readJson(path.join(pkgRoot,'package.json'));if(!pkg)continue;const declaration=await declarationText(pkgRoot,pkg);if(!declaration)continue;const exported=new Set([...declaration.matchAll(/export\s+(?:declare\s+)?(?:const|let|var|function|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)|export\s*\{([^}]+)\}/g)].flatMap(m=>m[1]?[m[1]]:(m[2]||'').split(',').map(x=>x.trim().split(/\s+as\s+/).pop())));for(const requested of match[1].split(',').map(x=>x.trim().split(/\s+as\s+/)[0]).filter(Boolean))if(!exported.has(requested)){const line=source.slice(0,match.index).split('\n').length;findings.push({...issue('installed-api-truth','high',path.relative(root,file).split(path.sep).join('/'),`${requested} is not exported by installed ${name}@${pkg.version}.`,`api:${name}:${pkg.version}:${requested}:${file}`,'Use an API exported by the installed version or update the dependency deliberately.','installed_verified'),line});}}}return findings;}
async function declarationText(pkgRoot,pkg){for(const candidate of [pkg.types,pkg.typings,'index.d.ts'].filter(Boolean)){try{return await fs.readFile(path.join(pkgRoot,candidate),'utf8');}catch{}}return null;}
function issue(ruleId,severity,file,message,fingerprint,remediation,level){return{id:`PP-${fingerprint}`,ruleId,title:ruleId.replaceAll('-',' '),severity,cwe:'CWE-1104',file,line:1,column:1,message,evidence:{snippet:'',rationale:message},verification:{level,method:'supply-chain-analysis',executed:false},remediation,confidence:0.96,fingerprint};}
async function readJson(file){try{return JSON.parse(await fs.readFile(file,'utf8'));}catch{return null;}}
